USE [DBTRILHA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_TRL_CARS](
	[idCar] [int] IDENTITY(1,1) NOT NULL,
	[nameCar] [varchar](50) NULL,
	[versionCar] [varchar](50) NULL,
	[yearCar] [varchar](4) NULL,
	[hourValueCar] [decimal](5, 2) NULL,
 CONSTRAINT [PK_TB_TRL_CARS] PRIMARY KEY CLUSTERED 
(
	[idCar] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


